import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700", "300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={almarai.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
